[supabase]
SUPABASE_URL = "https://okfqmujpbnoworkfbzqc.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rZnFtdWpwYm5vd29ya2ZienFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0NTI2MjEsImV4cCI6MjA3ODAyODYyMX0.WQYmtxbQwQWRv6eKIjKb5xtlVpeOdP64jLTbL093thM"

