SUPABASE_URL = "https://fjuafvxgkxkllpytclsf.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqdWFmdnhna3hrbGxweXRjbHNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2NTg4OTksImV4cCI6MjA3NzIzNDg5OX0.w9kgxV4PZQy13Sdds8NeAmo4mniMwUdHv0u6hZOyxr4"


N8N_WEBHOOK_URL = "https://alejandroalejandros.app.n8n.cloud/webhook/price-check"
